# <font color='#d50283'>IT Academy - Ciència de Dades (online)</font>
## Tasca M3 T01: 
### Exercicis de programació numèrica.
### Juan Javier Hidalgo Gómez

### <font color='#d50283'>- Exercici 1</font>
*Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.*

In [171]:
import numpy as np

# Defenir funciónes
 
def lista(n):
    #n=round(random.uniform(3,10))
    lista = []
    #n=3
    for i in range(n):
        lista.append(round(np.random.uniform(0,10)))
    #lista.sort()
    return lista

def D1_matrix(N,elementos):
    array= np.array(lista(elementos),ndmin=N)
    return array


#Cuerpo

matrix=D1_matrix(1,100)

if matrix.ndim != 1: 
    print(f'El Array generado es diferente a 1 dimensión, tiene {matrix.ndim} dimensiones\n')
else: 
    #calculo de la moda para numpy
    vals, counts = np.unique(matrix, return_counts=True)
    mode_value = vals[counts == np.max(counts)]
    print(f'Resultado:\n Número de dimensiones: {matrix.ndim}\n Array:\n{matrix}\n')
    print(f'Resumen estadístico:')
    print(f' Media arítmetica:{np.mean(matrix)}\n Mediana:{np.median(matrix)}\n Moda:{mode_value} ')
    print(f' Desviación típica:{np.std(matrix)}\n Varianza:{np.var(matrix)} ')
    print(f' Correlacion:{np.corrcoef(matrix)}\n Covarianza:{np.cov(matrix)} ')   
    
print('\nFin')



Resultado:
 Número de dimensiones: 1
 Array:
[ 4  5  5  8 10  8  1  8  1  2  2  2  5  7  5 10  2  8  9  6  5  6  4  6
  4  4  7  1  2  9  8  3  4  9  8  6  2  0  4  7  8  9  0  2  3  2  8  8
  5 10  1  9  1  2  7  1  6  4  7  9  8  8  0  3  5  4  2  3  9  3  4  0
  8  2  2  3  9  2  8  8  9  1  2  7  2  3  2  2  5  1  3  4  0  4  1  5
  8  8  1  6]

Resumen estadístico:
 Media arítmetica:4.74
 Mediana:4.0
 Moda:[2] 
 Desviación típica:2.944893886033926
 Varianza:8.6724 
 Correlacion:1.0
 Covarianza:8.760000000000002 

Fin


### <font color='#d50283'>- Exercici 2</font>
*Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.*

In [172]:

import numpy as np

# Defenir funciónes
def NxN_matrix(N,elementos):
    array = np.random.randint(elementos, size=(N,N)) 
    return array


#Cuerpo

n=10
elementos=100

matrix=NxN_matrix(n,elementos)
    
    
print(f'Resultado:\n Dimensión: {matrix.ndim}\n Cuadrado de {n}x{n}\n Números de {0} a {elementos}\n Array:\n{matrix}')   
print('\nFin')


Resultado:
 Dimensión: 2
 Cuadrado de 10x10
 Números de 0 a 100
 Array:
[[ 6 13 77 17 40 94 68 18  2 27]
 [ 8 79 51 87 47 63 30 13 92 46]
 [14 46 45 97  4 10 63 18 72 58]
 [73 13 12 29 78 77  9 46 60 76]
 [29 75 24 59 72 15 54 32 80 11]
 [15 25 21 22 81 92 91 72 91 92]
 [99 30 41  9 52 43 81 50 16 64]
 [26  7 54 82 58 75 57 58 76 13]
 [72 18 17 42 44 98 75 87 70 78]
 [46 54 50 43 65 78  6 47 44  9]]

Fin


### <font color='#d50283'>- Exercici 3</font>
*Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.*

In [184]:
import numpy as np

# Defenir funciónes
def NxN_matrix(N,M,elementos):
    array = np.random.randint(elementos, size=(N,M)) 
    return array


#Cuerpo

n=10
m=15
elementos=100

matrix=NxN_matrix(n,m,elementos)
    
    
print(f'Resultado:\n Dimensión: {matrix.ndim}\n Dos dimensiones de {n}x{m}\n Números de {0} a {elementos}\n Array:\n{matrix}')   
print(f' \n Total de Filas:\n {np.sum(matrix,axis=1)}\n Total de Columnas:\n {np.sum(matrix,axis=0)}')   
print('\nFin')

Resultado:
 Dimensión: 2
 Dos dimensiones de 10x15
 Números de 0 a 100
 Array:
[[33 77  1  3 39 62 62 27 58 98 47 25 80 73 25]
 [64 15 80  7 23 40 38 37 68 98 86 60 49 30 97]
 [91 71 77 89 37 31 49 47 53  8 18 84 25 39 93]
 [ 2 50 81 97  3 26 53 88 63 94 57 65 82 71 43]
 [69 58 40 19 34 85 88 94 65  0 88 47  4 64 36]
 [60 50 55 84 68  5 61 78 22 79 83 76 61 39 32]
 [57 30 84 20 58 69 74 88 75 21 70 65 52 13 79]
 [43 85 67 93  9 54 88 55 55 56 49 20 37 53 61]
 [83 40 67 37  3 84 38 94 33 89 41 22 66 57 27]
 [58 28 60 99 47 33 25 74 72 81 89  7 51 29 39]]
 
 Total de Filas:
 [710 792 812 875 791 853 855 825 781 792]
 Total de Columnas:
 [560 504 612 548 321 489 576 682 564 624 628 471 507 468 532]

Fin


### <font color='#d50283'>- Exercici 4</font>
*Implementa manualment una funció que calculi el coeficient de correlació. Informa-te*\'*n sobre els seus usos i interpretació.*

 ## $r=\frac{\sum[(x_i-\bar x)][(y_i-\bar y)]}{\sqrt{\sum(x_i-\bar x)^2*\sum(y_i-\bar y)^2}}$ 
    

In [7]:
import numpy as np

# Defenir funciónes
def NxN_matrix(N,M,elementos):
    array = np.random.randint(elementos, size=(N,M)) 
    return array

def coef_correlacio(a,fx,fy):
    #separamos las dos listas de nuestra matriz(Suponemos dos variables)
    Varible_x=a[fx]
    Varible_y=a[fy]

    ##### Calculo del coeficiente de Correción
    Xi= sum(Varible_x)
    Yi= sum(Varible_y)
    N=len(Varible_x)
    
    #print(Yi)
    Datosx=[]
    Totalx=0

    for x in range(0,len(Varible_x)):
        valor=Varible_x[x]*Varible_x[x]
        Datosx.append(valor)
        Totalx+=valor
        #print(TotalA2)
        
    # Elevar datos iniciales al cuadrado y sumarlos    
    Xi2 = sum(pow(Varible_x,2))
    Yi2 = sum(pow(Varible_y,2))
    #print(Yi2)
    # Multiplicar los dos arrays
    XiYi = sum(np.multiply(Varible_x,Varible_y))
    #Calculamos la media
    _X =Xi/N
    _Y =Yi/N
    #print(_Y )
    
    #Cálculo
    Varianza_X= ((Xi2/N)-pow(_X,2))
    #print(Varianza_X)
    DesviacionT_X= np.sqrt(Varianza_X)
    #print(DesviacionT_X)
    Varianza_Y= ((Yi2/N)-pow(_Y,2))
    #print(Varianza_Y)
    DesviacionT_Y= np.sqrt(Varianza_Y)
    #print(DesviacionT_Y)
    #Calcular la CooVarianza
    CooVarianza=(XiYi/N)-(np.multiply(_X,_Y))
    #print(CooVarianza)

    #Calcular Coeficiente de correlacion

    r=CooVarianza/(DesviacionT_X*DesviacionT_Y)
   
    return r

#Cuerpo

n=7
m=10
elementos=10

matrix=NxN_matrix(n,m,elementos)

# Se a definido para comparar diferentes vectores
Vector1=0
Vector2=1
resultado=coef_correlacio(matrix,Vector1,Vector2)
   
print(f'Resultado:\n Dimensión: {matrix.ndim}\n Dos dimensiones de {n}x{m}\n Números de {0} a {elementos}\n Array:\n{matrix}')   
print(f'\nResumen estadístico:')
print(f' Correlacion(cálculo manual):\n {round(resultado,3)}\n ')  
print(f' Correlacion(Método numpy):\n {round(np.corrcoef(matrix)[Vector1,Vector2],3)}\n ')   
   
print('\nFin')

Resultado:
 Dimensión: 2
 Dos dimensiones de 7x10
 Números de 0 a 10
 Array:
[[0 0 9 5 3 5 4 9 7 9]
 [2 6 6 1 5 5 4 4 3 5]
 [3 5 7 2 1 7 0 6 6 1]
 [5 4 9 4 3 7 7 5 0 9]
 [9 8 7 5 5 2 6 6 4 8]
 [7 4 8 5 3 3 6 9 9 0]
 [9 4 0 9 1 0 2 0 9 6]]

Resumen estadístico:
 Correlacion(cálculo manual):
 0.153
 
 Correlacion(Método numpy):
 0.153
 

Fin


***Coeficiente de Correlación***

Nos permite estudiar la relación entre dos variables continuas.  Valores positivos
nos indican que cambian en la misma dirección (directamente proporcional) o valores
negativos que indica que cambian en direcciones opuestas (inversamente proporcional).

Su valor está comprendido en el rango [+1 , -1]. Siendo +1 una correlación positiva perfecta y -1 una correlación negativa perfecta.

Se emplean como medida de la fuerza de asociación entre dos variables (tamaño del efecto):

- 0: asociación nula.
- 0.1: asociación pequeña.
- 0.3: asociación mediana.
- 0.5: asociación moderada.
- 0.7: asociación alta.
- 0.9: asociación muy alta.
